import {
    faCoins,
    faTimes,
    faStar,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faHourglassStart,
    faAngleDoubleUp,
    faArrowRight,
    faBolt,
    faRocket,
    faClock,
    faInfoCircle,
    faQuestion,
    faGift,
    faExternalLinkAlt,
    faCopy,
    faCheck,
  } from '@fortawesome/free-solid-svg-icons';
  
  export const icons = {
    coins: faCoins,
    times: faTimes,
    star: faStar,
    chevronLeft: faChevronLeft,
    chevronRight: faChevronRight,
    chevronUp: faChevronUp,
    chevronDown: faChevronDown,
    check : faCheck,
    hourglassStart: faHourglassStart,
    angleDoubleUp: faAngleDoubleUp,
    arrowRight : faArrowRight,
    bolt: faBolt,
    rocket : faRocket,
    clock: faClock,
    infoCircle : faInfoCircle,
    question : faQuestion,
    gift : faGift,
    externalLinkAlt : faExternalLinkAlt,
    copy : faCopy,
  };