-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyCardRewardClaimed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dailyRewardDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dailyRewardDay" INTEGER NOT NULL DEFAULT 1;
